---
- name: Update and upgrade apt packages
  become: yes
  apt:
    upgrade: "yes"
    update_cache: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: "Install Node.js 13"
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_lts.x | sudo -E bash -
    sudo apt-get install -y nodejs
    sudo npm install -g n
    sudo n 13.8.0


- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
