---
- name: Update and upgrade apt packages
  become: yes
  apt:
    upgrade: "yes"
    update_cache: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: download node.js 18 from nodesource.com website
  become: true
  shell: |
    curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash -


- name: "install node.js 18"
  become: yes
  apt:
    name: ["nodejs"]
    state: latest
    update_cache: yes


- name: "install pm2"
  become: yes
  npm:
    name: pm2
    global: yes
    production: yes
    state: present
