---
- name: "Create Backend app directory"
  file: 
    path: ~/backend-package
    state: directory


- name: "Unarchive backend files from local to EC2 instance"
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-package
  

- name: Installing Backend node packages
  shell: |
    cd ~/backend-package
    npm install

- name: executing node app with PM2
  shell: |
    cd ~/backend-package/dist
    pm2 stop default
    pm2 start main.js

  register: execute_node

- name: print message
  debug:
    msg: "{{ execute_node.stdout_lines }}"

 
- name: "Configure pm2 to start as service"
  shell: |
    sudo su -c "env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu"
    pm2 save