---
- name: "Create Backend app directory"
  file: 
    path: ~/backend-package
    state: directory


- name: unarchive files of artifact.tar.gz to EC2 instance server
  unarchive:
    src: artifact.tar.gz
    dest: ~/backend-package

- name: Installing Backend node packages
  shell: |
    cd ~/backend-package
    npm install

- name: executing node app with PM2
  shell: |
    cd ~/backend-package/dist
    pm2 stop default
    pm2 start main.js

  register: execute_node

- name: print message
  debug:
    msg: "{{execute_node.stdout_line}}"
  
- name: "configure pm2 to start as a service"
  become: true
  shell: |
    env PATH=$PATH:/user/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu
