---
- name: "Create Backend app directory"
  file: 
    path: ~/backend-package
    state: directory

- name: Copy file
  copy:
    src: artifact.tar.gz
    dest: ~/

- name: Unarchive a file that is already on the remote machine
  unarchive:
    src: ~/artifact.tar.gz
    dest: ~/backend-package
    remote_src: yes
  

- name: Installing Backend node packages
  shell: |
    cd ~/backend-package
    npm install

- name: executing node app with PM2
  shell: |
    cd ~/backend-package/dist
    pm2 stop default
    pm2 start main.js

  register: execute_node

- name: print message
  debug:
    msg: "{{execute_node.stdout_line}}"

 
- name: "Configure pm2 to start as service"
  shell: |
    sudo su -c "env PATH=$PATH:/usr/local/bin pm2 startup systemd -u ubuntu --hp /home/ubuntu"
    pm2 save