---
- name: "Create Backend app directory"
  file: 
    path: ~/backend-package
    state: directory


- name: unarchive files of artifact.tar.gz to EC2 instance server
  template:
    src: artifact.tar.gz
    dest: ~/backend-package

- name: Installing Backend node packages
  shell: |
    cd ~/backend-package
    npm install

- name: Starting the app
  shell: |
    pm2 stop default
    pm2 start npm -- start
    echo 'service started'