---
- name: Copy files to EC2 instance server
  template:
    src: "artifact.tar.gz"
    dest: "~/artifact.tar.gz"

- name: Extracting artifact.tar.gz file
  shell: |
    tar -xvzf ~/artifact.tar.gz

- name: Starting the app
  shell: |
    npm install
    pm2 stop default
    pm2 start npm -- start
    echo 'service started'