version: '2.1'
orbs:
  slack: circleci/slack@4.1


jobs:
  build_frontend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          command: |
            cd frontend
            npm i
      - save_cache:
          key: "frontend_npm_packages"
          paths:
            - /src/node_modules  
      - run: pwd 
      - run: cd frontend ; npm run build   


  build_backend:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - checkout
      - run:
          command: |
            cd backend
            npm i      
      - save_cache:
          key: "backend_npm_packages"
          paths:
            - /src/node_modules
      - run: pwd
      - run: cd backend ; npm run build 



workflows:
  my_workflow:
    jobs:
      - build_frontend
      - build_backend